
{{ config(materialized='view') }}

SELECT S.ISLAND,S.TOTAL_DEATHS FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_KAPIL_SRIVATSAN_1" S 
JOIN (SELECT MAX(TOTAL_DEATHS) AS TOT_DEATHS FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_KAPIL_SRIVATSAN_1" GROUP BY ISLAND) MAX
ON S.TOTAL_DEATHS=MAX.TOT_DEATHS
WHERE S.ISLAND IN ('Jawa','Papua''Kalimantan''Nusa Tenggara','Sumatera','Sulawesi','Maluku') ORDER BY TOTAL_DEATHS DESC LIMIT 1
